### ISSUE TITLE
2141bis: Section 3.3.2 q-component clarification

### ISSUE THREAD

**Issue by MelindaShore** [MelindaShore/urnbis#2]
From John:

> In section 3.3.2 on q-component, it seems reasonable to add a
> bit of explanation, thereby providing some protection from
> people who might assume they know what 3986 says without
> checking it (especially given the ABNF issues with that
> document).  I propose something like:
> 
>   "Note that "?" is not a special character after its
>   first instance introduces a q-component (assuming one is
>   allowed by the namespace).   "?" appearing later in a
>   q-component or in an f-component does not require
>   %-escaping except as required on a per-namespace basis."
> 
> Is that roughly correct?  What we want?
> 
> There is also another issue with that paragraph.  Given the
> "syntax only" principle, it is not clear that unquoted "?" must
> be prohibited from appearing in the NSS and/or p-component (if
> we think that is distinct).  The argument for prohibiting it is
> potential confusion.  The argument for allowing it is that it
> might be needed for externally-defined name spaces for which
> %-encoding would either be clutter or actually problematic.

**Comment by klensin** [comment]
2015-01-21: I think this one is settled unless someone complains on-list. However, since there are _two_ (or maybe three) substantive issues hidden in this, I have put a placeholder into the text (as of -09c) rather than changing it.  Those issues are:

(0) Does 3986 disallow "?" from appearing in <query> (without %-encoding) and should we say something about that?  Given that the very clear text in 3986 managed to confuse Andy and has confused a lot of others, the answers are pretty clearly "it doesn't" and "yes, we should say something".   A note to that effect is now in -09c. 

(1) Should we disallow "?" from appearing within a <query> even though 2141 does not require that?  I think the answer is "no reason to do that", but it may be worth further confirming that with the WG..

(2) Should we say something about embedded question marks as delimiters for name-value pairs?  In my personal capacity, I feel quite strongly that the answer should be "yes", but haven seen nearly enough clear support for that view to starting changing the text.

See http://www.ietf.org/mail-archive/web/urn/current/msg02725.html, several notes from probably a year or more ago, and some pieces of I-Ds that I can locate and drag out if needed.

**Comment by klensin** [comment]
Text has been clarified to make it clear that "?" is allowed, without encoding, within q-components (after the question mark that introduces those components) and f-components.  There have been no substantive comments about any of the other issues identified above.

**Comment by klensin** [comment]
Above clarifications are present in 2141bis-11.   The text may need further work if q-component is subdivided, e.g., along the lines of Keith's "??" proposal, but I'm starting a separate tracker entry for that, so this one can probably be closed.

**Comment by klensin** [comment]
See tracker item #13, '"Component" Information associated with URN processing versus to be passed to objects, URLs, etc.', for the "??" proposal and it context.
